In [1]:
import pandas as pd

In [3]:
customers = pd.read_csv(r"C:\Users\hp\salomi\customers.csv.txt",sep=",")
products = pd.read_csv(r"C:\Users\hp\salomi\products.csv.txt",sep=",")
orders_jan = pd.read_csv(r"C:\Users\hp\salomi\orders_jan.csv.txt",sep=",")
orders_feb = pd.read_csv(r"C:\Users\hp\salomi\orders_feb.csv.txt",sep=",")

In [ ]:
#Task 1: Append Monthly Orders

In [5]:
#Append data
fact_orders = pd.concat([orders_jan, orders_feb], ignore_index=True)

In [7]:
#Print result
print(fact_orders)

   order_id  customer_id product_id  quantity  order_date
0     O1001          101       P101         1  2024-01-05
1     O1002          102       P102         2  2024-01-08
2     O1003          103       P104         1  2024-01-10
3     O1004          104       P105         3  2024-01-12
4     O1005          105       P103         2  2024-01-15
5     O1006          106       P106         1  2024-01-18
6     O1007          107       P101         1  2024-01-20
7     O1008          108       P107         4  2024-01-25
8     O1009          109       P102         1  2024-02-03
9     O1010          110       P104         2  2024-02-05
10    O1011          101       P105         1  2024-02-08
11    O1012          102       P101         1  2024-02-10
12    O1013          103       P103         3  2024-02-14
13    O1014          104       P106         2  2024-02-18
14    O1015          105       P108         1  2024-02-20
15    O1016          106       P107         5  2024-02-25

In [9]:
# Total records
print("Total Orders:", len(fact_orders))

Total Orders: 16

In [ ]:
# Basic checks

In [11]:
fact_orders.head()

  order_id  customer_id product_id  quantity  order_date
0    O1001          101       P101         1  2024-01-05
1    O1002          102       P102         2  2024-01-08
2    O1003          103       P104         1  2024-01-10
3    O1004          104       P105         3  2024-01-12
4    O1005          105       P103         2  2024-01-15

In [13]:
fact_orders.shape

(16, 5)

In [15]:
fact_orders.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date'], dtype='object')

In [17]:
fact_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     16 non-null     object
 1   customer_id  16 non-null     int64
 2   product_id   16 non-null     object
 3   quantity     16 non-null     int64
 4   order_date   16 non-null     object
dtypes: int64(2), object(3)
memory usage: 772.0+ bytes

In [19]:
fact_orders.isnull().sum()

order_id       0
customer_id    0
product_id     0
quantity       0
order_date     0
dtype: int64

In [21]:
fact_orders["product_id"].nunique()

8

In [23]:
fact_orders.describe()

       customer_id   quantity
count    16.000000  16.000000
mean    104.750000   1.937500
std       2.768875   1.236595
min     101.000000   1.000000
25%     102.750000   1.000000
50%     104.500000   1.500000
75%     106.250000   2.250000
max     110.000000   5.000000

In [ ]:
#Task 2: Filter Electronics Orders

In [25]:
products

  product_id product_name     category  price
0       P101       Laptop  Electronics   1200
1       P102       Mobile  Electronics    800
2       P103   Headphones  Electronics    150
3       P104         Desk    Furniture    300
4       P105        Chair    Furniture    200
5       P106      Monitor  Electronics    400
6       P107     Keyboard  Electronics     80
7       P108      Printer  Electronics    250

In [27]:
orders_products = pd.merge(fact_orders, products, how="inner", on="product_id")

electronics_orders = orders_products[orders_products["category"] == "Electronics"]

print(electronics_orders)

   order_id  customer_id product_id  quantity  order_date product_name  \
0     O1001          101       P101         1  2024-01-05       Laptop
1     O1002          102       P102         2  2024-01-08       Mobile
4     O1005          105       P103         2  2024-01-15   Headphones
5     O1006          106       P106         1  2024-01-18      Monitor
6     O1007          107       P101         1  2024-01-20       Laptop
7     O1008          108       P107         4  2024-01-25     Keyboard
8     O1009          109       P102         1  2024-02-03       Mobile
11    O1012          102       P101         1  2024-02-10       Laptop
12    O1013          103       P103         3  2024-02-14   Headphones
13    O1014          104       P106         2  2024-02-18      Monitor
14    O1015          105       P108         1  2024-02-20      Printer
15    O1016          106       P107         5  2024-02-25     Keyboard

       category  price
0   Electronics   1200
1   Electronics    800
4   Electronics    150
5   Electronics    400
6   Electronics   1200
7   Electronics     80
8   Electronics    800
11  Electronics   1200
12  Electronics    150
13  Electronics    400
14  Electronics    250
15  Electronics     80

In [ ]:
#Task 3: Create Revenue Column

In [29]:
orders_products["revenue"] = (
    orders_products["quantity"] *
    orders_products["price"]
)

print(
    orders_products[
        ["order_id", "quantity", "price", "revenue"]
    ]
)

   order_id  quantity  price  revenue
0     O1001         1   1200     1200
1     O1002         2    800     1600
2     O1003         1    300      300
3     O1004         3    200      600
4     O1005         2    150      300
5     O1006         1    400      400
6     O1007         1   1200     1200
7     O1008         4     80      320
8     O1009         1    800      800
9     O1010         2    300      600
10    O1011         1    200      200
11    O1012         1   1200     1200
12    O1013         3    150      450
13    O1014         2    400      800
14    O1015         1    250      250
15    O1016         5     80      400

In [ ]:
#Task 4 - Customer Purchase Summary

In [31]:
customer_summary = (
    orders_products
    .groupby("customer_id")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("revenue", "sum")
    )
    .reset_index()
)

customer_summary

   customer_id  total_orders  total_revenue
0          101             2           1400
1          102             2           2800
2          103             2            750
3          104             2           1400
4          105             2            550
5          106             2            800
6          107             1           1200
7          108             1            320
8          109             1            800
9          110             1            600

In [ ]:
#Task 5 - Top 3 Revenue Generating Customers

In [33]:
top3 = customer_summary.sort_values(
    by="total_revenue",
    ascending=False
).head(3)

top3

   customer_id  total_orders  total_revenue
1          102             2           2800
0          101             2           1400
3          104             2           1400

In [ ]:
#Task 6 - State_Wise Revenue Analysis

In [35]:
state_data = pd.merge(
    orders_products,
    customers,
    on="customer_id"
)

state_revenue = (
    state_data
    .groupby("state")
    ["revenue"]
    .sum()
    .reset_index()
)

state_revenue

  state  revenue
0    FL      800
1    IL     2200
2    MA      320
3    TX     5350
4    WA     1950

In [ ]:
#Task 7 - Product Category Performance

In [37]:
category_performance = (
    orders_products
    .groupby("category")
    .agg(
        qty=("quantity", "sum"),
        revenue=("revenue", "sum")
    )
    .reset_index()
)

category_performance

      category  qty  revenue
0  Electronics   24     8920
1    Furniture    7     1700

In [ ]:
#Task 8: Customers With No Orders

In [39]:
customer_orders = pd.merge(customers,fact_orders,how="left",on="customer_id")

no_orders = customer_orders[
    customer_orders["order_id"].isnull()
]

no_orders

Empty DataFrame
Columns: [customer_id, customer_name, city, state, signup_date, order_id, product_id, quantity, order_date]
Index: []

In [ ]:
#Task 9: Monthly Revenue Trend

In [41]:
orders_products["order_date"] = pd.to_datetime(
    orders_products["order_date"]
)

orders_products["month"] = (
    orders_products["order_date"]
    .dt.month_name()
)

monthly_revenue = (
    orders_products
    .groupby("month")
    ["revenue"]
    .sum()
    .reset_index()
)

monthly_revenue

      month  revenue
0  February     4700
1   January     5920

In [ ]:
#Task 10: Top Product Per Category

In [43]:
product_revenue = (
    orders_products
    .groupby(["category", "product_name"])
    ["revenue"]
    .sum()
    .reset_index()
)

product_revenue["rank"] = (
    product_revenue
    .groupby("category")
    ["revenue"]
    .rank(method="first", ascending=False)
)

top_product = product_revenue[
    product_revenue["rank"] == 1
]

top_product

      category product_name  revenue  rank
2  Electronics       Laptop     3600   1.0
7    Furniture         Desk      900   1.0

In [ ]:
#Task 11: Data Quality Validation

In [ ]:
#Duplicate Order IDs

In [ ]:
fact_orders.groupby("order_id").size().reset_index(name="count")

In [ ]:
#Null Customer IDs

In [47]:
fact_orders[
    fact_orders["customer_id"].isnull()
]

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [ ]:
#Invalid Product IDs

In [45]:
fact_orders[
    ~fact_orders["product_id"].isin(
     products["product_id"]
    )
]

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [ ]:
#Task 12: Incremental Load Scenario

In [49]:
 orders_mar = pd.read_csv(r"C:\Users\hp\salomi\orders_mar.csv.txt",sep=",")

In [51]:
orders_mar

  order_id  customer_id product_id  quantity  order_date
0    O1017          107       P106         1  2024-03-02
1    O1018          108       P103         2  2024-03-05
2    O1019          109       P101         1  2024-03-08

In [53]:
incremental_data = orders_mar[~orders_mar['order_id'].isin(fact_orders['order_id'])]

In [55]:
fact_orders = pd.concat([fact_orders, incremental_data], ignore_index=True)

In [57]:
fact_orders

   order_id  customer_id product_id  quantity  order_date
0     O1001          101       P101         1  2024-01-05
1     O1002          102       P102         2  2024-01-08
2     O1003          103       P104         1  2024-01-10
3     O1004          104       P105         3  2024-01-12
4     O1005          105       P103         2  2024-01-15
5     O1006          106       P106         1  2024-01-18
6     O1007          107       P101         1  2024-01-20
7     O1008          108       P107         4  2024-01-25
8     O1009          109       P102         1  2024-02-03
9     O1010          110       P104         2  2024-02-05
10    O1011          101       P105         1  2024-02-08
11    O1012          102       P101         1  2024-02-10
12    O1013          103       P103         3  2024-02-14
13    O1014          104       P106         2  2024-02-18
14    O1015          105       P108         1  2024-02-20
15    O1016          106       P107         5  2024-02-25
16    O1017          107       P106         1  2024-03-02
17    O1018          108       P103         2  2024-03-05
18    O1019          109       P101         1  2024-03-08

In [ ]:
#Task 13
Find repeat customers who purchased in both January and February.

In [59]:
jan_customers = set(orders_jan['customer_id'].unique())

In [61]:
feb_customers = set(orders_feb['customer_id'].unique())

In [63]:
repeat_customers = jan_customers.intersection(feb_customers)

In [65]:
print(list(repeat_customers))

[101, 102, 103, 104, 105, 106]

In [ ]:
#Task 14
Calculate customer retention rate.

In [67]:
total_jan_customers = len(jan_customers)

In [69]:
total_repeat_customers = len(repeat_customers)

In [71]:
retention_rate = (total_repeat_customers / total_jan_customers) * 100

In [73]:
print(f"Customer Retention Rate: {retention_rate:.2f}%")

Customer Retention Rate: 75.00%

In [ ]:
#Task 15
Find customers whose revenue is above average revenue.
Use:
AVG()
and subqueries.

In [75]:
#Average Revenue Calculate
avg_revenue = customer_summary["total_revenue"].mean()

print(avg_revenue)

1062.0

In [77]:
#Above Average Customers
above_avg_customers = customer_summary[
    customer_summary["total_revenue"] > avg_revenue
]

print(above_avg_customers)

   customer_id  total_orders  total_revenue
0          101             2           1400
1          102             2           2800
3          104             2           1400
6          107             1           1200

In [ ]:
#Task 16: Sales Leaderboard

In [79]:
#Revenue Descending Sort
leaderboard = customer_summary.sort_values(
    by="total_revenue",
    ascending=False
)

In [81]:
#Rank Create
leaderboard["rank"] = (
    leaderboard["total_revenue"]
    .rank(method="dense", ascending=False)
)

In [83]:
print(
    leaderboard[
        ["rank", "customer_id", "total_revenue"]
    ]
)

   rank  customer_id  total_revenue
1   1.0          102           2800
0   2.0          101           1400
3   2.0          104           1400
6   3.0          107           1200
5   4.0          106            800
8   4.0          109            800
2   5.0          103            750
9   6.0          110            600
4   7.0          105            550
7   8.0          108            320

In [ ]:
#Task 17: Build a Star Schema

In [85]:
#dim_customer Create
dim_customer = customers.copy()

dim_customer["customer_key"] = range(
    1,
    len(dim_customer)+1
)

dim_customer = dim_customer[
    [
        "customer_key",
        "customer_id",
        "customer_name",
        "city",
        "state",
        "signup_date"
    ]
]

dim_customer

   customer_key  customer_id  customer_name     city state signup_date
0             1          101     John Smith   Dallas    TX  2023-01-15
1             2          102      Sarah Lee   Austin    TX  2023-02-10
2             3          103  Michael Brown  Seattle    WA  2023-03-05
3             4          104    Emma Wilson  Chicago    IL  2023-03-20
4             5          105    David Clark   Dallas    TX  2023-04-10
5             6          106    Olivia Hall    Miami    FL  2023-05-01
6             7          107    James Young  Seattle    WA  2023-05-15
7             8          108    Sophia King   Boston    MA  2023-06-01
8             9          109   Daniel Scott  Chicago    IL  2023-06-10
9            10          110      Ava Green   Austin    TX  2023-06-15

In [87]:
#dim_product Create
dim_product = products.copy()

dim_product["product_key"] = range(
    1,
    len(dim_product)+1
)

dim_product = dim_product[
    [
        "product_key",
        "product_id",
        "product_name",
        "category",
        "price"
    ]
]

dim_product

   product_key product_id product_name     category  price
0            1       P101       Laptop  Electronics   1200
1            2       P102       Mobile  Electronics    800
2            3       P103   Headphones  Electronics    150
3            4       P104         Desk    Furniture    300
4            5       P105        Chair    Furniture    200
5            6       P106      Monitor  Electronics    400
6            7       P107     Keyboard  Electronics     80
7            8       P108      Printer  Electronics    250

In [89]:
#dim_date Create
dim_date = fact_orders.copy()

dim_date["order_date"] = pd.to_datetime(
    dim_date["order_date"]
)

dim_date = dim_date[
    ["order_date"]
].drop_duplicates()

dim_date["date_key"] = range(
    1,
    len(dim_date)+1
)

dim_date["month"] = (
    dim_date["order_date"]
    .dt.month
)

dim_date["year"] = (
    dim_date["order_date"]
    .dt.year
)

dim_date["quarter"] = (
    dim_date["order_date"]
    .dt.quarter
)

dim_date

   order_date  date_key  month  year  quarter
0  2024-01-05         1      1  2024        1
1  2024-01-08         2      1  2024        1
2  2024-01-10         3      1  2024        1
3  2024-01-12         4      1  2024        1
4  2024-01-15         5      1  2024        1
5  2024-01-18         6      1  2024        1
6  2024-01-20         7      1  2024        1
7  2024-01-25         8      1  2024        1
8  2024-02-03         9      2  2024        1
9  2024-02-05        10      2  2024        1
10 2024-02-08        11      2  2024        1
11 2024-02-10        12      2  2024        1
12 2024-02-14        13      2  2024        1
13 2024-02-18        14      2  2024        1
14 2024-02-20        15      2  2024        1
15 2024-02-25        16      2  2024        1
16 2024-03-02        17      3  2024        1
17 2024-03-05        18      3  2024        1
18 2024-03-08        19      3  2024        1

In [91]:
#Revenue Column Create
orders_products["revenue"] = (
    orders_products["quantity"]
    *
    orders_products["price"]
)

In [93]:
#Fact Table Create
fact_table = pd.merge(
    orders_products,
    dim_customer[
        ["customer_key","customer_id"]
    ],
    on="customer_id"
)

fact_table = pd.merge(
    fact_table,
    dim_product[
        ["product_key","product_id"]
    ],
    on="product_id"
)

fact_table = pd.merge(
    fact_table,
    dim_date[
        ["date_key","order_date"]
    ],
    on="order_date"
)

fact_table

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,revenue,month,customer_key,product_key,date_key
0,O1001,101,P101,1,2024-01-05,Laptop,Electronics,1200,1200,January,1,1,1
1,O1002,102,P102,2,2024-01-08,Mobile,Electronics,800,1600,January,2,2,2
2,O1003,103,P104,1,2024-01-10,Desk,Furniture,300,300,January,3,4,3
3,O1004,104,P105,3,2024-01-12,Chair,Furniture,200,600,January,4,5,4
4,O1005,105,P103,2,2024-01-15,Headphones,Electronics,150,300,January,5,3,5
5,O1006,106,P106,1,2024-01-18,Monitor,Electronics,400,400,January,6,6,6
6,O1007,107,P101,1,2024-01-20,Laptop,Electronics,1200,1200,January,7,1,7
7,O1008,108,P107,4,2024-01-25,Keyboard,Electronics,80,320,January,8,7,8
8,O1009,109,P102,1,2024-02-03,Mobile,Electronics,800,800,February,9,2,9
9,O1010,110,P104,2,2024-02-05,Desk,Furniture,300,600,February,10,4,10
10,O1011,101,P105,1,2024-02-08,Chair,Furniture,200,200,February,1,5,11
11,O1012,102,P101,1,2024-02-10,Laptop,Electronics,1200,1200,February,2,1,12
12,O1013,103,P103,3,2024-02-14,Headphones,Electronics,150,450,February,3,3,13
13,O1014,104,P106,2,2024-02-18,Monitor,Electronics,400,800,February,4,6,14
14,O1015,105,P108,1,2024-02-20,Printer,Electronics,250,250,February,5,8,15
15,O1016,106,P107,5,2024-02-25,Keyboard,Electronics,80,400,February,6,7,16

In [ ]:
#Required Columns

In [95]:
fact_orders_star = fact_table[
    [
        "order_id",
        "customer_key",
        "product_key",
        "date_key",
        "quantity",
        "revenue"
    ]
]

fact_orders_star

   order_id  customer_key  product_key  date_key  quantity  revenue
0     O1001             1            1         1         1     1200
1     O1002             2            2         2         2     1600
2     O1003             3            4         3         1      300
3     O1004             4            5         4         3      600
4     O1005             5            3         5         2      300
5     O1006             6            6         6         1      400
6     O1007             7            1         7         1     1200
7     O1008             8            7         8         4      320
8     O1009             9            2         9         1      800
9     O1010            10            4        10         2      600
10    O1011             1            5        11         1      200
11    O1012             2            1        12         1     1200
12    O1013             3            3        13         3      450
13    O1014             4            6        14         2      800
14    O1015             5            8        15         1      250
15    O1016             6            7        16         5      400